[project]
name = "amq2-service-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Facundo Adrián Lucianna", email = "facundolucianna@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "awswrangler>=3.17.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "mlflow>=3.16.1",
    "optuna>=5.0.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
amq2-service-ml = "amq2_service_ml:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
